name: Deploy to Azure Web App

on:
  workflow_dispatch:  # Permite activarlo manualmente desde GitHub
  # push:
  #   branches:
  #     - main       # ⚠️ Descomentá si querés que se despliegue automáticamente al hacer push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy WebApi to Azure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish .NET Core Project
        run: |
          dotnet publish src/ProyectoBase/WebApi.csproj -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  # 👈 Nombre de la App en Azure (ej: arquetipo-pablo)
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish
