name: Build and Test .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/ProyectoBase/ProyectoBase.sln

      - name: Build
        run: dotnet build src/ProyectoBase/ProyectoBase.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test src/ProyectoBase/ProyectoBase.sln --no-build --verbosity normal --logger trx

