name: .NET Build, Test & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/ProyectoBase/ProyectoBase.sln

    - name: Build
      run: dotnet build src/ProyectoBase/ProyectoBase.sln --no-restore --configuration Release

    - name: Test with coverage
      run: |
        dotnet test src/ProyectoBase.Tests/ProyectoBase.Tests.csproj \
          --no-build \
          --configuration Release \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=cobertura \
          /p:CoverletOutput=TestResults/coverage.xml

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate coverage report
      run: |
        reportgenerator \
          -reports:src/ProyectoBase.Tests/TestResults/coverage.xml \
          -targetdir:coveragereport \
          -reporttypes:HtmlInline_AzurePipelines

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coveragereport


